/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.map.CadastroProdutos.gui;

import br.edu.map.CadastroProdutos.dao.ProdutoDAO;
import br.edu.map.CadastroProdutos.model.Produto;
import br.edu.map.CadastroProdutos.util.MensagensUtil;
import java.awt.Color;
import javax.swing.ImageIcon;
//import java.util.Date;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Washington
 */

public class ProdutoJFrame extends javax.swing.JFrame {
    
    private ProdutosJFrame parent;
    private ProdutoDAO produtoDAO;
    private Produto produto;
    
    /**
     * Creates new form ClienteJFrame
     */
    
    public ProdutoJFrame(ProdutosJFrame parent, Produto produto) {
        this.parent = parent;
        this.produtoDAO = new ProdutoDAO();
        this.produto = produto;
        setTitle(MensagensUtil.getMensagem(MensagensUtil.TITULO_FRAME_PRODUTO));

        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        preencherCampos();
    }

    private void preencherCampos() {
        if (produto != null) {
            this.labelTitulo.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_EDITAR_TITULO));

            this.textNome.setText(produto.getNome());
            this.textPreco.setText(Double.toString(produto.getPreco()));
            this.textFabricante.setText(produto.getEspecificacao().getFabricante());
            this.textCor.setText(produto.getEspecificacao().getCor());
            this.textSistema.setText(produto.getEspecificacao().getSistema());
            this.textAreaDetalhes.setText(produto.getEspecificacao().getDetalhes());
            this.setIconImage(new ImageIcon(getClass().getResource("/img/editar.png")).getImage());
        } else {
            this.labelTitulo.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_NOVO_TITULO));
            this.setIconImage(new ImageIcon(getClass().getResource("/img/novo.png")).getImage());
        }

        this.labelNome.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_NOME));
        this.labelPreco.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_PRECO));
        this.labelCor.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_COR));
        this.labelFabricante.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_FABRICANTE));
        this.labelSistema.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_SISTEMA));
        this.labelDetalhes.setText(MensagensUtil.getMensagem(MensagensUtil.LABEL_DETALHES));
        this.buttonSalvar.setText(MensagensUtil.getMensagem(MensagensUtil.BUTTON_SALVAR));
        this.buttonCancelar.setText(MensagensUtil.getMensagem(MensagensUtil.BUTTON_CANCELAR));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        textPreco = new javax.swing.JTextField();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        labelFabricante = new javax.swing.JLabel();
        textFabricante = new javax.swing.JTextField();
        labelCor = new javax.swing.JLabel();
        textCor = new javax.swing.JTextField();
        labelSistema = new javax.swing.JLabel();
        textSistema = new javax.swing.JTextField();
        labelDetalhes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDetalhes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Novo Produto");

        labelNome.setText("Nome");

        labelPreco.setText("Preço");

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        labelFabricante.setText("Fabricante");

        labelCor.setText("Cor");

        labelSistema.setText("Sistema");

        labelDetalhes.setText("Detalhes");

        textAreaDetalhes.setColumns(20);
        textAreaDetalhes.setRows(5);
        jScrollPane1.setViewportView(textAreaDetalhes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(textNome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textPreco)
                    .addComponent(textFabricante)
                    .addComponent(textCor)
                    .addComponent(textSistema)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelPreco)
                            .addComponent(labelFabricante)
                            .addComponent(labelCor)
                            .addComponent(labelSistema)
                            .addComponent(labelDetalhes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNome)
                .addGap(1, 1, 1)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPreco)
                .addGap(1, 1, 1)
                .addComponent(textPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFabricante)
                .addGap(1, 1, 1)
                .addComponent(textFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCor)
                .addGap(1, 1, 1)
                .addComponent(textCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSistema)
                .addGap(1, 1, 1)
                .addComponent(textSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDetalhes)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarCampos() throws Exception {
        if (textNome.getText() == null || textNome.getText().equals("")) {
            textNome.requestFocus();
            textNome.setBackground(new Color(255, 198, 194));
            throw new Exception(MensagensUtil.getMensagem(MensagensUtil.MSG_VALIDACAO_NOME));
        }
        if (textPreco.getText() == null || textPreco.getText().equals("")) {
            textPreco.requestFocus();
            textPreco.setBackground(new Color(255, 198, 194));
            throw new Exception(MensagensUtil.getMensagem(MensagensUtil.MSG_VALIDACAO_PRECO));
        }
    }
    
    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        
        try {
            
            validarCampos();
            
            if (produto != null) {

                produto.setNome(textNome.getText());
                produto.setPreco(Double.valueOf(textPreco.getText()));
                produto.getEspecificacao().setFabricante(textFabricante.getText());
                produto.getEspecificacao().setCor(textCor.getText());
                produto.getEspecificacao().setSistema(textSistema.getText());
                produto.getEspecificacao().setDetalhes(textAreaDetalhes.getText());
                
                produtoDAO.editar(produto);

            } else {

                Produto p = new Produto();
                
                p.setNome(textNome.getText());
                p.setPreco(Double.parseDouble(textPreco.getText()));
                p.getEspecificacao().setFabricante(textFabricante.getText());
                p.getEspecificacao().setCor(textCor.getText());
                p.getEspecificacao().setSistema(textSistema.getText());
                p.getEspecificacao().setDetalhes(textAreaDetalhes.getText());
                
                produtoDAO.inserir(p);
            }

            parent.preencherTabela(null);

            dispose();
           
        } catch (Exception ex) {
            //ex.printStackTrace();
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Erro : " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void textNomeFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:

        if (textNome.getText() != null && !textNome.getText().equals("")) {
            textNome.setBackground(Color.white);
        }
    }           
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelDetalhes;
    private javax.swing.JLabel labelFabricante;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelSistema;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea textAreaDetalhes;
    private javax.swing.JTextField textCor;
    private javax.swing.JTextField textFabricante;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textPreco;
    private javax.swing.JTextField textSistema;
    // End of variables declaration//GEN-END:variables
}
